"""empty message

Revision ID: 766d76a95577
Revises: 7c508aea5c9d
Create Date: 2022-04-22 17:24:11.182282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d76a95577'
down_revision = '7c508aea5c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('color', sa.String(length=80), nullable=False))
    op.add_column('Cars', sa.Column('transmission', sa.String(length=200), nullable=False))
    op.drop_column('Cars', 'transmision')
    op.drop_column('Cars', 'colour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('colour', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('Cars', sa.Column('transmision', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('Cars', 'transmission')
    op.drop_column('Cars', 'color')
    # ### end Alembic commands ###
