"""empty message

Revision ID: 7c508aea5c9d
Revises: 03ff5e83654a
Create Date: 2022-04-22 17:07:49.985367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c508aea5c9d'
down_revision = '03ff5e83654a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('description', sa.String(length=80), nullable=False))
    op.add_column('Cars', sa.Column('image', sa.String(length=80), nullable=False))
    op.drop_column('Cars', 'photo')
    op.drop_column('Cars', 'discription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('discription', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('Cars', sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('Cars', 'image')
    op.drop_column('Cars', 'description')
    # ### end Alembic commands ###
