"""empty message

Revision ID: 8cc5f686814b
Revises: 766d76a95577
Create Date: 2022-04-22 18:24:05.731757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc5f686814b'
down_revision = '766d76a95577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Cars_user_id_fkey', 'Cars', type_='foreignkey')
    op.drop_constraint('Favourites_user_id_fkey', 'Favourites', type_='foreignkey')
    op.drop_constraint('Favourites_car_id_fkey', 'Favourites', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Favourites_car_id_fkey', 'Favourites', 'Cars', ['car_id'], ['id'])
    op.create_foreign_key('Favourites_user_id_fkey', 'Favourites', 'Users', ['user_id'], ['id'])
    op.create_foreign_key('Cars_user_id_fkey', 'Cars', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###
