"""empty message
Revision ID: ca1f5a99ba8a
Revises: 
Create Date: 2020-05-07 13:30:14.919734
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1f5a99ba8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table('Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discription', sa.String(length=80), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('colour', sa.String(length=80), nullable=False),
    sa.Column('year', sa.String(length=120), nullable=False),
    sa.Column('transmision', sa.String(length=200), nullable=False),
    sa.Column('car_type', sa.String(length=80), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),                 
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_uc')
    )
    op.create_table('Favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'user_id', name='_car_user_uc')
    )
    
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('biography', sa.String(length=1000), nullable=False),
    sa.Column('profile_photo', sa.String(length=200), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cars')
    op.drop_table('Favourites')
    op.drop_table('Users')
    # ### end Alembic commands ###
